# Generated by Django 3.2.9 on 2021-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='desc',
            field=models.TextField(default='Test', max_length=100),
        ),
    ]
